name: VOICHAT CI&CD

on: push

jobs:
  chatwork-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Chatwork
      run: |
        curl \
          -X POST "https://api.chatwork.com/v2/rooms/${{ vars.CHATWORK_ROOM_ID }}/messages" \
          -H "X-ChatWorkToken: ${{ vars.CHATWORK_API_TOKEN }}" \
          -d <<-EOS "body=
          [info][title]VOICHAT[/title]
          ${GITHUB_REF}
          ${GITHUB_ACTOR}
          ${{ github.event.head_commit.message }}
          ${GITHUB_SHA}
          [/info]"
          EOS
